services:
  - type: web
    name: personal-safety-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free
    region: frankfurt
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_VAPID_PUBLIC_KEY
        value: BCR9hC4I8CGfY2X5RZmR_CC8-0zi8ITFHDSzhVO4CXiVoZ-1CFrFU7m-ev6EW_FmURjacesDcojC47H6BtZSEII
      - key: VAPID_PRIVATE_KEY
        value: -iJ4fJhTLRfiJ_YfkSmBzeXpPqJEP97e67Mi4lue2dY
      - key: VAPID_SUBJECT
        value: mailto:security@personal-safety.app
      - key: ALERTS_API_TOKEN
        value: f2184a0fd1d14c5aa291368854cbe654d178883fab2203
