name = "personal-safety-backend"
main = "src/index.ts"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]

# [triggers]
# crons = ["* * * * *"]

[[kv_namespaces]]
binding = "PSA_STORAGE"
id = "8d7944ad493e4455b7bd517a5784417f"

[vars]
ENVIRONMENT = "production"
NEXT_PUBLIC_VAPID_PUBLIC_KEY = "BCR9hC4I8CGfY2X5RZmR_CC8-0zi8ITFHDSzhVO4CXiVoZ-1CFrFU7m-ev6EW_FmURjacesDcojC47H6BtZSEII"
VAPID_PRIVATE_KEY = "-iJ4fJhTLRfiJ_YfkSmBzeXpPqJEP97e67Mi4lue2dY"
VAPID_SUBJECT = "mailto:security@personal-safety.app"
ALERTS_API_TOKEN = "f2184a0fd1d14c5aa291368854cbe654d178883fab2203"
