name = "personal-safety-backend"
main = "src/index.ts"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]
account_id = "7532116e9d16abfc6b7eded7a89c4f72"
workers_dev = true

# Cloudflare Workers Configuration ($0 / Free Tier)
# Private secrets (VAPID_PRIVATE_KEY, ALERTS_API_TOKEN) are injected via Cloudflare Worker Secrets

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "PSA_STORAGE"
id = "8d7944ad493e4455b7bd517a5784417f"

[vars]
ENVIRONMENT = "production"
NEXT_PUBLIC_VAPID_PUBLIC_KEY = "BFM9HkzYgwAYdTY5VYhj_Gfm39qhGL5vs7vy9iuj1-vBt8eXFqH9j0wh7qgh2_ScpX-LWhIKfHogc7wgSl0flRk"
VAPID_SUBJECT = "mailto:security@personal-safety.app"

